# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CarHireTarget' do
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'FTUtils', '~> 1.1.1'
pod 'FlurrySDK', '~>6.6.0'
end

